name: release
on:
  create:
    tags:
      - v*
jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Cache modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
